neoimmo/src/Entity/Bien.php
<?php

namespace App\Entity;

use App\Repository\BienRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BienRepository::class)]
class Bien
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $titre = null;

    #[ORM\Column(length: 3000)]
    private ?string $Contenu = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Url_Photo = null;

    #[ORM\Column(length: 50)]
    private ?string $Code_postal = null;

    #[ORM\Column]
    private ?int $Numero_de_ladresse = null;

    #[ORM\Column(length: 255)]
    private ?string $Nom_de_la_voie = null;

    #[ORM\Column(length: 50)]
    private ?string $Prix = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $Date_annonce = null;

    #[ORM\Column(length: 50)]
    private ?string $Type = null;

    #[ORM\ManyToOne(inversedBy: 'id_bien')]
    private ?User $user = null;

    #[ORM\ManyToMany(targetEntity: Form::class, inversedBy: 'id_bien')]
    private Collection $form;

    #[ORM\Column]
    private ?int $superficie = null;

    #[ORM\Column(length: 255)]
    private ?string $type_annonce = null;

    #[ORM\Column]
    private ?bool $jardin = null;

    #[ORM\Column]
    private ?bool $balcon = null;

    #[ORM\Column]
    private ?bool $parking = null;

    public function __construct()
    {
        $this->form = new ArrayCollection();
    }

    // public function __toString(): string
    // {
    //     return $this->city.' '.$this->year;
    // }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->Contenu;
    }

    public function setContenu(string $Contenu): self
    {
        $this->Contenu = $Contenu;

        return $this;
    }

    public function getUrlPhoto(): ?string
    {
        return $this->Url_Photo;
    }

    public function setUrlPhoto(?string $Url_Photo): self
    {
        $this->Url_Photo = $Url_Photo;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->Code_postal;
    }

    public function setCodePostal(string $Code_postal): self
    {
        $this->Code_postal = $Code_postal;

        return $this;
    }

    public function getNumeroDeLadresse(): ?int
    {
        return $this->Numero_de_ladresse;
    }

    public function setNumeroDeLadresse(int $Numero_de_ladresse): self
    {
        $this->Numero_de_ladresse = $Numero_de_ladresse;

        return $this;
    }

    public function getNomDeLaVoie(): ?string
    {
        return $this->Nom_de_la_voie;
    }

    public function setNomDeLaVoie(string $Nom_de_la_voie): self
    {
        $this->Nom_de_la_voie = $Nom_de_la_voie;

        return $this;
    }

    public function getPrix(): ?string
    {
        return $this->Prix;
    }

    public function setPrix(string $Prix): self
    {
        $this->Prix = $Prix;

        return $this;
    }

    public function getDateAnnonce(): ?\DateTimeInterface
    {
        return $this->Date_annonce;
    }

    public function setDateAnnonce(\DateTimeInterface $Date_annonce): self
    {
        $this->Date_annonce = $Date_annonce;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->Type;
    }

    public function setType(string $Type): self
    {
        $this->Type = $Type;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, Form>
     */
    public function getForm(): Collection
    {
        return $this->form;
    }

    public function addForm(Form $form): self
    {
        if (!$this->form->contains($form)) {
            $this->form->add($form);
        }

        return $this;
    }

    public function removeForm(Form $form): self
    {
        $this->form->removeElement($form);

        return $this;
    }

    public function getSuperficie(): ?int
    {
        return $this->superficie;
    }

    public function setSuperficie(int $superficie): self
    {
        $this->superficie = $superficie;

        return $this;
    }

    public function getTypeAnnonce(): ?string
    {
        return $this->type_annonce;
    }

    public function setTypeAnnonce(string $type_annonce): self
    {
        $this->type_annonce = $type_annonce;

        return $this;
    }

    public function isJardin(): ?bool
    {
        return $this->jardin;
    }

    public function setJardin(bool $jardin): self
    {
        $this->jardin = $jardin;

        return $this;
    }

    public function isBalcon(): ?bool
    {
        return $this->balcon;
    }

    public function setBalcon(bool $balcon): self
    {
        $this->balcon = $balcon;

        return $this;
    }

    public function isParking(): ?bool
    {
        return $this->parking;
    }

    public function setParking(bool $parking): self
    {
        $this->parking = $parking;

        return $this;
    }
}

neoimmo/src/Controller/BienController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Bien;
use App\Repository\BienRepository;

class BienController extends AbstractController
{
    #[Route('/bien', name: 'app_bien')]
    public function index(BienRepository $bien): Response
    {
        $data = $bien->findAll();
        return $this->render('bien/catalogue.html.twig', [
            'biens' => $data,
        ]);
    }
    #[Route('/bien/fiche/{id}', name: 'app_fiche_bien')]
    public function showFiche(BienRepository $bien, $id): Response
    {
        $data = $bien->find($id);
        return $this->render('bien/ficheBien.html.twig', [
            'bien' => $data,
        ]);
    }
}

neoimmo/templates/bien/catalogue.html.twig
{% extends 'base.html.twig' %}

{% block title %}Catalogue de Bien{% endblock %}

{% block body %}
{% for row in biens %}
<div id="catalogueCard">
<div class="card"  id="cataloguePlacement" style="width: 18rem;">
  <a href="/bien/fiche/{{ row.id }}"> <img src="{{ asset ('asset/images/') ~ row.urlPhoto}}" class="card-img-top" alt="..."> </a>
    <div class="card-body" style="height:24vh">
      <h5 class="card-title">{{ row.titre }} {{row.typeAnnonce}}</h5>
      <p style="height:5rem;" class="card-text">Parking : {{row.parking}} <br> Balcon : {{row.balcon}} <br> Jardin : {{row.jardin}} <br> Superficie : {{row.superficie}} m²</p>
    </div>
    <ul class="list-group list-group-flush centered">
      <li class="list-group-item">{{ row.dateAnnonce | date('d/m/y') }}</li>
    </ul>
    </div>
  </div>
</div>

{# <div id="catalogue">
    <h2> {{ row.titre }} {{ row.Prix }} {{ row.Type }} {{ row.dateAnnonce | date('d/m/y') }}</h2>
    <img src={{ asset ('asset/images/') ~ row.urlPhoto}} alt="">
</div> #}
    
{% endfor %}
{% endblock %}

neoimmo/templates/bien/ficheBien.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello FicheBienController!{% endblock %}

{% block body %}


  <div class="card mb-3" style="margin:5vw 5vh">
    <img class="card-img-top" id="imagio" src="{{ asset ('asset/images/') ~ bien.urlPhoto}}" alt="Card image cap">
        <h1 class="card-title">{{bien.titre}}</h1>
      <div class="card-text" id="card-text">{{bien.contenu}}</div>
      <br><br><hr>
      <p>Parking : {{bien.parking}} <br> Balcon : {{bien.balcon}} <br> Jardin : {{bien.jardin}} <br> Superficie : {{bien.superficie}} m²<br> Cette appartement est disponnible en {{bien.typeAnnonce}} </p>
      
  </div>

  <!--Section: Contact v.2-->
  {% include '/Form/contactForm.html.twig' %}

{% endblock %}